export const MOCK_GYMS = [
 { id: '1', slug: 'iron-temple', name: 'Iron Temple', address: '123 Main St, Beverly Hills, CA 90210', distance: 0.8, rating: 4.8, reviewCount: 312, monthlyPrice: 39, joinFee: 0, contractLength: 'None', is24hr: true, hasPool: false, hasSauna: true, parking: true, classCount: 12, corporateRate: 29, lat: 34.0736, lng: -118.4004, amenities: ['Free weights', 'Machines', 'Cardio', 'Sauna', 'Showers', 'Lockers'], classes: ['HIIT', 'Yoga', 'Spinning', 'Boxing'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [7,8,17,18,19] },
 { id: '2', slug: 'fitlife-247', name: 'FitLife 24/7', address: '456 Sunset Blvd, Los Angeles, CA 90028', distance: 1.2, rating: 4.2, reviewCount: 187, monthlyPrice: 29, joinFee: 49, contractLength: '12 months', is24hr: true, hasPool: false, hasSauna: false, parking: true, classCount: 8, corporateRate: 22, lat: 34.0983, lng: -118.3268, amenities: ['Free weights', 'Machines', 'Cardio', 'Showers', 'Lockers'], classes: ['HIIT', 'Yoga', 'CrossFit'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [6,7,17,18] },
 { id: '3', slug: 'peak-athletics', name: 'Peak Athletics', address: '789 Wilshire Blvd, Santa Monica, CA 90401', distance: 2.1, rating: 4.9, reviewCount: 98, monthlyPrice: 59, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: true, hasSauna: true, parking: true, classCount: 20, corporateRate: 45, lat: 34.0195, lng: -118.4912, amenities: ['Free weights', 'Machines', 'Cardio', 'Pool', 'Sauna', 'Basketball', 'Showers', 'Lockers', 'Towel service'], classes: ['HIIT', 'Yoga', 'Spinning', 'Boxing', 'Pilates', 'Swimming'], hours: { weekday: '5am - 11pm', weekend: '6am - 9pm' }, peakHours: [7,8,9,17,18,19] },
 { id: '4', slug: 'flex-factory', name: 'Flex Factory', address: '321 Venice Blvd, Venice, CA 90291', distance: 3.5, rating: 4.5, reviewCount: 245, monthlyPrice: 35, joinFee: 25, contractLength: '6 months', is24hr: false, hasPool: false, hasSauna: false, parking: false, classCount: 15, corporateRate: 28, lat: 33.9925, lng: -118.4614, amenities: ['Free weights', 'Machines', 'Cardio', 'Functional training', 'Showers'], classes: ['CrossFit', 'HIIT', 'Boxing', 'Strength'], hours: { weekday: '5am - 10pm', weekend: '7am - 8pm' }, peakHours: [6,7,17,18] },
 { id: '5', slug: 'zen-fitness', name: 'Zen Fitness', address: '555 Ocean Ave, Santa Monica, CA 90402', distance: 2.8, rating: 4.7, reviewCount: 156, monthlyPrice: 49, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: true, hasSauna: true, parking: true, classCount: 25, corporateRate: 38, lat: 34.0259, lng: -118.5057, amenities: ['Free weights', 'Machines', 'Cardio', 'Pool', 'Sauna', 'Spa', 'Yoga studio', 'Showers', 'Lockers'], classes: ['Yoga', 'Pilates', 'Meditation', 'Barre', 'Swimming', 'HIIT'], hours: { weekday: '5am - 10pm', weekend: '6am - 9pm' }, peakHours: [8,9,10,17,18] },
 { id: '6', slug: 'muscle-lab', name: 'Muscle Lab', address: '888 La Brea Ave, Los Angeles, CA 90036', distance: 4.2, rating: 4.6, reviewCount: 203, monthlyPrice: 45, joinFee: 0, contractLength: 'None', is24hr: true, hasPool: false, hasSauna: true, parking: true, classCount: 10, corporateRate: 35, lat: 34.0622, lng: -118.3437, amenities: ['Free weights', 'Powerlifting', 'Machines', 'Cardio', 'Sauna', 'Showers'], classes: ['Powerlifting', 'Strength', 'HIIT', 'Bodybuilding'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [7,8,16,17,18,19] },
  { id: '7', slug: 'empire-fitness', name: 'Empire Fitness', address: '350 5th Ave, New York, NY 10118', distance: 0.5, rating: 4.4, reviewCount: 421, monthlyPrice: 55, joinFee: 99, contractLength: '12 months', is24hr: false, hasPool: false, hasSauna: true, parking: false, classCount: 30, corporateRate: 42, lat: 40.7484, lng: -73.9856, amenities: ['Free weights', 'Machines', 'Cardio', 'Sauna', 'Boxing ring', 'Showers', 'Lockers'], classes: ['HIIT', 'Boxing', 'Spinning', 'Yoga', 'Pilates', 'Kickboxing'], hours: { weekday: '5am - 11pm', weekend: '6am - 10pm' }, peakHours: [6,7,8,17,18,19,20] },
  { id: '8', slug: 'liberty-gym', name: 'Liberty Gym', address: '200 Vesey St, New York, NY 10281', distance: 1.8, rating: 4.1, reviewCount: 189, monthlyPrice: 35, joinFee: 0, contractLength: 'None', is24hr: true, hasPool: false, hasSauna: false, parking: false, classCount: 6, corporateRate: 28, lat: 40.7127, lng: -74.0134, amenities: ['Free weights', 'Machines', 'Cardio', 'Showers'], classes: ['HIIT', 'Yoga', 'Strength'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [7,8,12,17,18] },
  { id: '9', slug: 'southside-strength', name: 'Southside Strength', address: '1400 S Michigan Ave, Chicago, IL 60605', distance: 1.1, rating: 4.7, reviewCount: 276, monthlyPrice: 42, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: false, hasSauna: true, parking: true, classCount: 14, corporateRate: 32, lat: 41.8621, lng: -87.6246, amenities: ['Free weights', 'Powerlifting', 'Machines', 'Cardio', 'Sauna', 'Showers', 'Lockers'], classes: ['Powerlifting', 'HIIT', 'Boxing', 'Strength', 'Olympic lifting'], hours: { weekday: '5am - 10pm', weekend: '6am - 8pm' }, peakHours: [6,7,17,18,19] },
  { id: '10', slug: 'lakefront-athletic-club', name: 'Lakefront Athletic Club', address: '211 N Stetson Ave, Chicago, IL 60601', distance: 2.4, rating: 4.8, reviewCount: 163, monthlyPrice: 75, joinFee: 150, contractLength: '12 months', is24hr: false, hasPool: true, hasSauna: true, parking: true, classCount: 35, corporateRate: 55, lat: 41.8867, lng: -87.6217, amenities: ['Free weights', 'Machines', 'Cardio', 'Pool', 'Sauna', 'Steam room', 'Basketball', 'Racquetball', 'Showers', 'Lockers', 'Towel service', 'Cafe'], classes: ['HIIT', 'Yoga', 'Pilates', 'Spinning', 'Swimming', 'Aqua fitness', 'Boxing', 'Barre'], hours: { weekday: '5am - 10pm', weekend: '6am - 9pm' }, peakHours: [6,7,8,12,17,18,19] },
  { id: '11', slug: 'lone-star-fitness', name: 'Lone Star Fitness', address: '500 Main St, Houston, TX 77002', distance: 0.9, rating: 4.3, reviewCount: 198, monthlyPrice: 25, joinFee: 0, contractLength: 'None', is24hr: true, hasPool: false, hasSauna: false, parking: true, classCount: 10, corporateRate: 20, lat: 29.7604, lng: -95.3698, amenities: ['Free weights', 'Machines', 'Cardio', 'Functional training', 'Showers', 'Lockers'], classes: ['HIIT', 'CrossFit', 'Yoga', 'Strength'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [5,6,7,17,18] },
  { id: '12', slug: 'bayou-city-barbell', name: 'Bayou City Barbell', address: '1919 Washington Ave, Houston, TX 77007', distance: 2.6, rating: 4.9, reviewCount: 87, monthlyPrice: 65, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: false, hasSauna: false, parking: true, classCount: 5, corporateRate: 50, lat: 29.7633, lng: -95.3817, amenities: ['Free weights', 'Powerlifting', 'Olympic platforms', 'Strongman equipment', 'Chalk allowed', 'Showers'], classes: ['Powerlifting', 'Olympic lifting', 'Strongman'], hours: { weekday: '6am - 9pm', weekend: '8am - 6pm' }, peakHours: [7,8,17,18] },
  { id: '13', slug: 'pacific-fitness', name: 'Pacific Fitness', address: '1455 Market St, San Francisco, CA 94103', distance: 0.7, rating: 4.5, reviewCount: 334, monthlyPrice: 60, joinFee: 50, contractLength: '6 months', is24hr: false, hasPool: true, hasSauna: true, parking: false, classCount: 28, corporateRate: 45, lat: 37.7749, lng: -122.4194, amenities: ['Free weights', 'Machines', 'Cardio', 'Pool', 'Sauna', 'Steam room', 'Yoga studio', 'Showers', 'Lockers', 'Towel service'], classes: ['HIIT', 'Yoga', 'Spinning', 'Swimming', 'Pilates', 'Boxing', 'TRX'], hours: { weekday: '5am - 10pm', weekend: '6am - 9pm' }, peakHours: [7,8,12,17,18,19] },
  { id: '14', slug: 'mission-crossfit', name: 'Mission CrossFit', address: '3450 26th St, San Francisco, CA 94110', distance: 3.1, rating: 4.6, reviewCount: 112, monthlyPrice: 185, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: false, hasSauna: false, parking: false, classCount: 40, corporateRate: 150, lat: 37.7485, lng: -122.4236, amenities: ['Functional training', 'Olympic platforms', 'Rowing machines', 'Assault bikes', 'Pull-up rigs', 'Showers'], classes: ['CrossFit', 'Olympic lifting', 'Gymnastics', 'Endurance', 'Mobility'], hours: { weekday: '5:30am - 8pm', weekend: '8am - 12pm' }, peakHours: [6,7,8,12,17,18] },
  { id: '15', slug: 'desert-iron', name: 'Desert Iron', address: '4350 E Camelback Rd, Phoenix, AZ 85018', distance: 1.5, rating: 4.4, reviewCount: 231, monthlyPrice: 30, joinFee: 29, contractLength: '6 months', is24hr: true, hasPool: false, hasSauna: true, parking: true, classCount: 12, corporateRate: 24, lat: 33.5088, lng: -111.9780, amenities: ['Free weights', 'Machines', 'Cardio', 'Sauna', 'Outdoor training area', 'Showers', 'Lockers'], classes: ['HIIT', 'Yoga', 'Spinning', 'Boot camp'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [5,6,7,18,19] },
  { id: '16', slug: 'summit-gym', name: 'Summit Gym', address: '1600 Broadway, Denver, CO 80202', distance: 0.6, rating: 4.7, reviewCount: 178, monthlyPrice: 48, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: false, hasSauna: true, parking: true, classCount: 18, corporateRate: 38, lat: 39.7392, lng: -104.9903, amenities: ['Free weights', 'Machines', 'Cardio', 'Sauna', 'Climbing wall', 'Functional training', 'Showers', 'Lockers'], classes: ['HIIT', 'Yoga', 'Rock climbing', 'Spinning', 'Boxing', 'Strength'], hours: { weekday: '5am - 10pm', weekend: '6am - 8pm' }, peakHours: [6,7,12,17,18] },
  { id: '17', slug: 'peachtree-fitness', name: 'Peachtree Fitness', address: '191 Peachtree St NE, Atlanta, GA 30303', distance: 1.3, rating: 4.3, reviewCount: 267, monthlyPrice: 32, joinFee: 0, contractLength: 'None', is24hr: true, hasPool: false, hasSauna: false, parking: true, classCount: 15, corporateRate: 25, lat: 33.7590, lng: -84.3880, amenities: ['Free weights', 'Machines', 'Cardio', 'Functional training', 'Showers', 'Lockers'], classes: ['HIIT', 'Yoga', 'Spinning', 'Kickboxing', 'Zumba'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [6,7,17,18,19] },
  { id: '18', slug: 'emerald-city-athletics', name: 'Emerald City Athletics', address: '400 Pine St, Seattle, WA 98101', distance: 0.8, rating: 4.6, reviewCount: 195, monthlyPrice: 52, joinFee: 0, contractLength: 'None', is24hr: false, hasPool: true, hasSauna: true, parking: false, classCount: 22, corporateRate: 40, lat: 47.6062, lng: -122.3321, amenities: ['Free weights', 'Machines', 'Cardio', 'Pool', 'Sauna', 'Yoga studio', 'Showers', 'Lockers', 'Towel service'], classes: ['HIIT', 'Yoga', 'Pilates', 'Swimming', 'Spinning', 'Boxing'], hours: { weekday: '5am - 10pm', weekend: '6am - 9pm' }, peakHours: [7,8,12,17,18,19] },
  { id: '19', slug: 'south-beach-gym', name: 'South Beach Gym', address: '235 Washington Ave, Miami Beach, FL 33139', distance: 1.0, rating: 4.5, reviewCount: 389, monthlyPrice: 40, joinFee: 0, contractLength: 'None', is24hr: true, hasPool: false, hasSauna: true, parking: false, classCount: 16, corporateRate: 30, lat: 25.7826, lng: -80.1340, amenities: ['Free weights', 'Machines', 'Cardio', 'Sauna', 'Outdoor area', 'Showers', 'Lockers'], classes: ['HIIT', 'Boxing', 'Yoga', 'Calisthenics', 'Spinning'], hours: { weekday: '24/7', weekend: '24/7' }, peakHours: [7,8,9,17,18,19] },
  { id: '20', slug: 'capitol-strength', name: 'Capitol Strength', address: '1331 Pennsylvania Ave NW, Washington, DC 20004', distance: 0.4, rating: 4.8, reviewCount: 142, monthlyPrice: 70, joinFee: 100, contractLength: '12 months', is24hr: false, hasPool: true, hasSauna: true, parking: true, classCount: 32, corporateRate: 52, lat: 38.8951, lng: -77.0364, amenities: ['Free weights', 'Machines', 'Cardio', 'Pool', 'Sauna', 'Steam room', 'Basketball', 'Squash', 'Showers', 'Lockers', 'Towel service', 'Cafe'], classes: ['HIIT', 'Yoga', 'Pilates', 'Spinning', 'Swimming', 'Boxing', 'Barre', 'TRX'], hours: { weekday: '5am - 10pm', weekend: '6am - 8pm' }, peakHours: [6,7,12,17,18,19] },
];

export const MOCK_REVIEWS = [
 { id: '1', gymId: '1', userName: 'Jake M.', rating: 5, body: 'Best gym in the area. Equipment is always clean and well-maintained. Staff is friendly and the 24/7 access is a game changer for my schedule.', date: '2026-08-10', verified: true },
 { id: '2', gymId: '1', userName: 'Sarah K.', rating: 4, body: 'Great equipment selection. Gets crowded during peak hours 5-7pm but otherwise excellent. The sauna is a nice bonus.', date: '2026-08-05', verified: true },
 { id: '3', gymId: '1', userName: 'Mike R.', rating: 5, body: 'Switched from FitLife and never looked back. Worth every penny. The free weights area is massive and never have to wait for a rack.', date: '2026-07-28', verified: true },
 { id: '4', gymId: '2', userName: 'Alex T.', rating: 4, body: 'Good value for money. Basic but has everything you need. The 12-month contract is a bit annoying though.', date: '2026-08-12', verified: true },
 { id: '5', gymId: '3', userName: 'Rachel P.', rating: 5, body: 'The pool is amazing. Classes are top notch and the instructors really know their stuff. Premium price but premium experience.', date: '2026-08-08', verified: true },
];

export const MOCK_CORPORATE_STATS = {
 activeMembers: 342,
 utilisationRate: 73,
 visitsThisMonth: 1247,
 costPerMember: 18.40,
 totalSeats: 468,
 monthlySpend: 7524,
 pendingInvites: 12,
 topGyms: [
 { name: 'Iron Temple', members: 87 },
 { name: 'FitLife 24/7', members: 64 },
 { name: 'Peak Athletics', members: 52 },
 { name: 'Zen Fitness', members: 41 },
 ],
 monthlyVisits: [890, 920, 980, 1050, 1100, 1180, 1220, 1247],
 months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug'],
};

export const MOCK_EMPLOYEES = [
 { id: '1', name: 'Sarah Chen', email: 'sarah.chen@acmecorp.com', gym: 'Iron Temple', status: 'active', joinedAt: '2026-02-15', visits: 18 },
 { id: '2', name: 'Mike Patel', email: 'mike.patel@acmecorp.com', gym: 'FitLife 24/7', status: 'active', joinedAt: '2026-03-01', visits: 14 },
 { id: '3', name: 'Alex Jones', email: 'alex.jones@acmecorp.com', gym: null, status: 'pending', joinedAt: null, visits: 0 },
 { id: '4', name: 'Lisa Wang', email: 'lisa.wang@acmecorp.com', gym: 'Peak Athletics', status: 'active', joinedAt: '2026-01-20', visits: 22 },
 { id: '5', name: 'David Kim', email: 'david.kim@acmecorp.com', gym: 'Iron Temple', status: 'active', joinedAt: '2026-04-10', visits: 11 },
 { id: '6', name: 'Emma Brown', email: 'emma.brown@acmecorp.com', gym: 'Zen Fitness', status: 'active', joinedAt: '2026-05-05', visits: 16 },
 { id: '7', name: 'James Wilson', email: 'james.wilson@acmecorp.com', gym: null, status: 'invited', joinedAt: null, visits: 0 },
 { id: '8', name: 'Nina Rodriguez', email: 'nina.r@acmecorp.com', gym: 'Flex Factory', status: 'active', joinedAt: '2026-03-20', visits: 9 },
];

export const MOCK_REFERRALS = [
 { id: '1', refereeName: 'Sarah J.', gym: 'Iron Temple', status: 'paid', amount: 15, date: '2026-08-01' },
 { id: '2', refereeName: 'Mike P.', gym: 'FitLife 24/7', status: 'paid', amount: 12, date: '2026-08-05' },
 { id: '3', refereeName: 'Alex K.', gym: 'Peak Athletics', status: 'pending', amount: 25, date: '2026-08-15' },
 { id: '4', refereeName: 'Lisa W.', gym: 'Iron Temple', status: 'recurring', amount: 5, date: '2026-08-01' },
];

export const MOCK_INVOICES = [
 { id: '1', period: 'August 2026', amount: 7524, status: 'pending', date: '2026-08-01' },
 { id: '2', period: 'July 2026', amount: 7308, status: 'paid', date: '2026-07-01' },
 { id: '3', period: 'June 2026', amount: 6952, status: 'paid', date: '2026-06-01' },
 { id: '4', period: 'May 2026', amount: 6720, status: 'paid', date: '2026-05-01' },
];
