'use client';
import Navbar from '@/components/layout/Navbar';
import { useParams } from 'next/navigation';
import { MOCK_GYMS } from '@/lib/mock-data';

export default function TrialPage() {
  const params = useParams();
  const gym = MOCK_GYMS.find(g => g.slug === params.slug) || MOCK_GYMS[0];

  return (<><Navbar /><main className="pt-16 min-h-screen flex items-center justify-center px-6"><div className="w-full max-w-lg"><div className="text-center mb-8"><h1 className="font-[var(--font-display)] text-3xl font-bold tracking-tight mb-2">Book a free trial</h1><p className="text-text2">Try {gym.name} for free. No commitment required.</p></div><div className="bg-card rounded-2xl border border-border p-8 space-y-4"><div className="grid grid-cols-2 gap-3"><div><label className="text-sm font-medium text-text2 block mb-1.5">First name</label><input placeholder="Jake" className="w-full px-4 py-3 rounded-xl border border-border bg-bg text-sm text-text outline-none focus:border-teal"/></div><div><label className="text-sm font-medium text-text2 block mb-1.5">Last name</label><input placeholder="Mitchell" className="w-full px-4 py-3 rounded-xl border border-border bg-bg text-sm text-text outline-none focus:border-teal"/></div></div><div><label className="text-sm font-medium text-text2 block mb-1.5">Email</label><input type="email" placeholder="you@example.com" className="w-full px-4 py-3 rounded-xl border border-border bg-bg text-sm text-text outline-none focus:border-teal"/></div><div><label className="text-sm font-medium text-text2 block mb-1.5">Preferred date</label><input type="date" className="w-full px-4 py-3 rounded-xl border border-border bg-bg text-sm text-text outline-none focus:border-teal"/></div><div><label className="text-sm font-medium text-text2 block mb-1.5">Time slot</label><select className="w-full px-4 py-3 rounded-xl border border-border bg-bg text-sm text-text2"><option>Morning (6am-12pm)</option><option>Afternoon (12pm-5pm)</option><option>Evening (5pm-10pm)</option></select></div><button className="w-full bg-teal text-white py-3 rounded-xl font-semibold text-[15px] hover:bg-teal-dark transition-colors">Book trial pass</button><div className="p-3 rounded-lg bg-green-light text-center"><p className="text-xs font-semibold text-green">Free trial · No credit card · No obligation</p></div></div></div></main></>);
}
